version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  user-service:
    build: ./services/user-service
    container_name: user-service
    restart: always
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://root:example@mongodb:27017/userdb?authSource=admin
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672
      - JWT_SECRET=nikunj
      - JWT_EXPIRY=24h
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      prometheus:
        condition: service_started
      grafana:
        condition: service_started

  notification-service:
    build: ./services/notification-service
    container_name: notification-service
    restart: always
    ports:
      - "3002:3002"
    environment:
      - MONGODB_URI=mongodb://root:example@mongodb:27017/notificationsdb?authSource=admin
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      prometheus:
        condition: service_started
      grafana:
        condition: service_started

  recommendation-service:
    build: ./services/recommendation-service
    container_name: recommendation-service
    restart: always
    ports:
      - "3003:3003"
    environment:
      - MONGODB_URI=mongodb://root:example@mongodb:27017/recommendationsdb?authSource=admin
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      prometheus:
        condition: service_started
      grafana:
        condition: service_started

  graphql-gateway:
    build: ./services/graphql-gateway
    container_name: graphql-gateway
    restart: always
    ports:
      - "4000:4000"
    environment:
      - MONGODB_URI=mongodb://root:example@mongodb:27017/gatewaydb?authSource=admin
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - USER_SERVICE_URL=http://user-service:3001
      - NOTIFICATION_SERVICE_URL=http://notification-service:3002
      - RECOMMENDATION_SERVICE_URL=http://recommendation-service:3003
    depends_on:
      redis:
        condition: service_healthy
      user-service:
        condition: service_started
      notification-service:
        condition: service_started
      recommendation-service:
        condition: service_started
      prometheus:
        condition: service_started
      grafana:
        condition: service_started

volumes:
  mongodb_data:
  grafana_data:
  redis_data:
