global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:3001']

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:3002']

  - job_name: 'recommendation-service'
    static_configs:
      - targets: ['recommendation-service:3003']

  - job_name: 'graphql-gateway'
    static_configs:
      - targets: ['graphql-gateway:4000']
